Unignore CVE-2022-30065
buildsec/frsca pull request #268
Opened 2022-07-20 14:09 UTC by bradbeck

The `alpine` image has been updated to remove this vulnerability, so there is no longer a reason to ignore it in a Grype scan.

Signed-off-by: Brad Beck <bradley.beck@gmail.com>

2022-07-20 18:34 UTC, rgreinho requested changes

2022-07-20 18:34 UTC, rgreinho commented on examples/examples.cue
> +		#      type: apk
Shouldn't we simply delete this block instead then?

2022-07-20 21:46 UTC, bradbeck commented on examples/examples.cue
> +		#      type: apk
I left it there as reference in case we need to ignore things in the future. Otherwise we'd have to go find the docs and figure out the format again.

But I can remove it if you don't think that is an issue.

2022-07-20 22:26 UTC, rgreinho commented on examples/examples.cue
> +		#      type: apk
Make sense 👍

2022-07-20 22:26 UTC, rgreinho approved these changes

2022-07-21 08:46 UTC, jondkent approved these changes
LGTM

2022-07-21 20:00 UTC, sudo-bmitch approved these changes

2022-07-21 20:00 UTC, merged