update script to use INSTALL_DIR
buildsec/frsca pull request #294
Opened 2022-08-04 17:14 UTC by anniepamela2020

This PR addresses the issue #276

2022-08-04 18:42 UTC, bradbeck commented on platform/00-kubernetes-minikube-setup.sh
> +      sudo tar xvzf $TKN_FILE_NAME $INSTALL_DIR tkn
```suggestion
      sudo tar xvzf $TKN_FILE_NAME -C $INSTALL_DIR tkn
```

2022-08-04 19:10 UTC, bradbeck approved these changes

2022-08-05 13:34 UTC, sudo-bmitch requested changes

2022-08-05 13:34 UTC, sudo-bmitch commented on platform/00-kubernetes-minikube-setup.sh
> +      sudo tar xvzf $TKN_FILE_NAME -C $INSTALL_DIR tkn
In the future, I'd like to make `$INSTALL_DIR` user configurable, so I recommend quoting it.

```suggestion
      sudo tar xvzf $TKN_FILE_NAME -C "$INSTALL_DIR" tkn
```

2022-08-05 13:43 UTC, sudo-bmitch approved these changes

2022-08-05 14:13 UTC, merged