Code of conduct
buildsec/frsca pull request #321
Opened 2022-09-08 03:17 UTC by anniepamela2020

Signed-off-by: Annie Pamela Kwengoua kwengouapamela@yahoo.com

Fixes the issue #312

2022-09-08 14:46 UTC, sudo-bmitch requested changes
Content LGTM. I would rename it to `CODE_OF_CONDUCT.md` so it gets treated as markdown.

2022-09-08 15:18 UTC, bradbeck commented
You'll need to have `Signed-off-by: ...` on each of your commits.

2022-09-12 15:13 UTC, bradbeck commented
Looks like the file name change got lost in the recent updates and still needs to be changed.

2022-09-13 20:05 UTC, bradbeck approved these changes

2022-09-13 21:44 UTC, sudo-bmitch approved these changes

2022-09-13 21:44 UTC, merged