fix: workflow issues found via scorecard
buildsec/frsca pull request #384
Opened 2023-01-05 19:54 UTC by pxp928

Signed-off-by: pxp928 <parth.psu@gmail.com>

Fixes the workflow issues found via the code scanning via scorecard. Specifically, pinned-dependencies and token permissions.

2023-01-05 20:09 UTC, bradbeck submitted a review, later dismissed

2023-01-10 21:37 UTC, sudo-bmitch requested changes

2023-01-10 21:46 UTC, pxp928 commented on .github/workflows/docs.yaml
> +      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
ugh lol.  I will fix this. Thanks!

2023-01-10 21:53 UTC, pxp928 commented
fixed!

2023-01-10 22:07 UTC, mlieberman85 approved these changes
LGTM

2023-01-10 23:46 UTC, sudo-bmitch approved these changes

2023-01-10 23:46 UTC, merged